---
title: "Benchmarking"
output: html_document
params:
  sce: "data/CyTOF/CyTOF-test.rds"
  input_dir: "output/v4/rare-subtype-benchmarking/"
  AL_pattern: "CyTOF-Active-Learning*-annotator-GroundTruth-knn_neighbors-NA-resolution-NA-iterations_set-*-cells*"
  seurat_pattern: "CyTOF-Seurat*-cells*"
  random_pattern: "CyTOF-random*-cells*"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '../../')
suppressPackageStartupMessages({
  library(tidyverse)
  library(yardstick)
})
source("../../pipeline/whatsthatcell-helpers.R")
```


```{r message=F}
### [ LOAD GROUND TRUTH ] #####
sce <- readRDS(params$sce)
sce_gt <- tibble(cell_id = colnames(sce),
                 annotated_cell_type = sce$CellType)

AL_files <- list.files(params$input_dir, 
                       pattern = glob2rx(params$AL_pattern),
                       full.names = TRUE)

Seurat_files <- list.files(params$input_dir,
                           pattern = glob2rx(params$seurat_pattern),
                           full.names = TRUE)
random_files <- list.files(params$input_dir,
                           pattern = glob2rx(params$random_pattern),
                           full.names = TRUE)

AL <- lapply(AL_files, read_tsv) %>% 
  bind_rows()
Seurat <- lapply(Seurat_files, read_tsv) %>% 
  bind_rows()
random <- lapply(random_files, read_tsv) %>% 
  bind_rows()
save.image('debug-benchmark.Rdata')
```


```{r}
predictions <- bind_rows(AL, Seurat, random) %>% 
  left_join(sce_gt) %>% 
  separate(prediction_params, c('m1', 'm2', 'rm_it', 'set', 'rm_knn', 'knn', 
                     'rm_res', 'res', 'rm_cell_num', 'cell_num', 'rm_rand', 'rand', 
                     'rm_corr', 'corrupted'), sep = '-') %>% 
  select(-starts_with('rm')) %>% 
  unite(method, c(m1, m2), sep = '-') %>% 
  mutate(selection_procedure = gsub("Active-Learning-strategy-", "", selection_procedure))

acc <- predictions %>% 
  filter(predicted_cell_type != "unassigned") %>%
  group_by(method, set, knn, res, cell_num, rand, corrupted, selection_procedure) %>% 
  acc_wrap() %>% 
  mutate(selection_procedure = gsub("_quant_entropy", "-AL", selection_procedure),
         selection_procedure = gsub("_entropy", "-AL", selection_procedure),
         selection_procedure = gsub("-strategy-NA", "", selection_procedure),
         cell_num = factor(cell_num, levels = c("50", "100", "250", "500")))


selection_order <- acc %>% 
  filter(rand == "0" | rand == "NA") %>% 
  filter(corrupted == "0") %>% 
  group_by(selection_procedure) %>% 
  summarise(mean_accuracy = mean(.estimate)) %>% 
  arrange(mean_accuracy) %>% 
  pull(selection_procedure)

acc %>% 
  filter(rand == "0" | rand == "NA") %>% 
  filter(corrupted == "0") %>% 
  mutate(selection_procedure = factor(selection_procedure, levels = selection_order)) %>% 
  ggplot(aes(x = selection_procedure, y = .estimate, color = method)) +
  geom_point() +
  ylim(0, 1) +
  labs(x = "Selection proceduce") +
  facet_grid(cell_num ~ .metric) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

```{r}
acc %>% 
  filter(rand == "0" | rand == "NA") %>% 
  filter(corrupted == "0") %>% 
  mutate(selection_procedure = factor(selection_procedure, levels = selection_order),
         plotting_group = paste0(set, "-", knn, "-", res, "-", selection_procedure)) %>% 
  ggplot(aes(x = cell_num, y = .estimate, color = selection_procedure, group = plotting_group)) +
  geom_point() +
  ylim(0, 1) +
  geom_line() +
  facet_grid(method ~ .metric) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

```{r}
lapply(unique(acc$method), function(x){
  acc %>% 
    filter(rand == "0") %>% 
    filter(method == x) %>% 
    ggplot(aes(x = corrupted, y = .estimate, color = selection_procedure, group = selection_procedure)) + 
    geom_point() +
    geom_line() +
    ylim(0, 1) +
    facet_grid(cell_num ~ .metric) + 
    theme_bw() + 
    labs(title = x, color = "Selection procedure", x = "Corrupted") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
})
```

```{r}
lapply(unique(acc$method), function(x){
  acc %>% 
    filter(corrupted == "0" & selection_procedure != "random" & selection_procedure != "Seurat-clustering") %>% 
    filter(method == x) %>% 
    ggplot(aes(x = rand, y = .estimate, color = selection_procedure, group = selection_procedure)) +
    geom_point() + 
    geom_line() +
    ylim(0, 1) +
    facet_grid(cell_num ~ .metric) + 
    theme_bw() + 
    labs(title = x, color = "Selection procedure", x = "Corrupted") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
})
```


```{r eval = F}
cell_type_accuracies <- function(predictions, cell_type){
  res <- predictions %>% 
    filter(annotated_cell_type == cell_type) %>% 
    filter(predicted_cell_type != "unassigned") %>% 
    #group_by(method, selection_procedure, prediction_params) %>% 
    group_by(method, set, knn, res, cell_num, rand, corrupted, selection_procedure) %>% 
    acc_wrap()
  
  res %>% 
    ggplot(aes(x = selection_procedure, y = .estimate)) +
    geom_point() +
    labs(title = cell_type) +
    facet_grid(method ~ .metric) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90))
}


lapply(unique(predictions$annotated_cell_type), function(x){
  cell_type_accuracies(predictions, x)
})


lapply(unique(predictions$method), function(x){
  a <- predictions %>% 
    filter(selection_procedure == "Active-Learning" & method == x)
  
  table(a$predicted_cell_type, a$annotated_cell_type)
})
```

